export let MANGA = {
	INDEX: {
		REQUEST: 'MANGA_INDEX_REQUEST',
		SUCCESS: 'MANGA_INDEX_SUCCESS',
		FAILURE: 'MANGA_INDEX_FAILURE',
		LOCK: 'MANGA_INDEX_LOCK'
	},
	TITLE: {
		REQUEST: 'MANGA_TITLE_REQUEST',
		SUCCESS: 'MANGA_TITLE_SUCCESS',
		FAILURE: 'MANGA_TITLE_FAILURE',
		LOCK: 'MANGA_TITLE_LOCK'
	},
	CHAPTER: {
		REQUEST: 'MANGA_CHAPTER_REQUEST',
		SUCCESS: 'MANGA_CHAPTER_SUCCESS',
		FAILURE: 'MANGA_CHAPTER_FAILURE',
		LOCK: 'MANGA_CHAPTER_LOCK'
	},
};

export let COLOR = {
	TOGGLE: 'COLOR_TOGGLE',
	SUGGEST: 'COLOR_SUGGEST',
	CONFIRM: 'COLOR_CONFIRM'
};

export let LOADING = {
	START: 'LOADING_START',
	FINISH: 'LOADING_FINISH'
};
